spring:
  application:
    name: ptal
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      url-decode: true
      use-trailing-slash-match: true
      matching-strategy: path_pattern_parser
# 로깅 설정
logging:
  level:
    ROOT: INFO
    org.springframework: DEBUG
    konkuk.ptal: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


# JWT 설정
jwt:
  secret: YmFzZTY0ZW5jb2RlZHNlY3JldGtleXN0cmluZ2hlcmU=
  access-token-expiration-ms: 3600000
  refresh-token-expiration-ms: 604800000
  header: Authorization
  prefix: Bearer

# SpringDoc OpenAPI 설정
springdoc:
  swagger-ui:
    # Swagger UI가 참조할 OpenAPI 스펙 파일의 경로 (클래스패스 기준)
    url: /openapi.yaml
    # 기본 API Docs 경로 (/v3/api-docs)를 비활성화하고 싶다면 (선택 사항)
    # path: /my-custom-swagger-ui-path.html # Swagger UI 접속 경로 변경 (선택 사항)
  api-docs:
    enabled: true # true가 기본값. 만약 YAML만 쓰고 자동생성 안할거면 false로. 하지만 보통은 true로 두고 YAML을 보조로 사용.
    # path: /my-api-docs # API 스펙 JSON/YAML 제공 경로 변경 (선택 사항)
  # 기본적으로 springdoc은 어노테이션 기반으로 API 문서를 생성.
  # 위 url 설정은 Swagger UI가 '추가적으로' 또는 '대체하여' 참조할 파일을 지정하는 것.
# code file 저장소
file:
  storage:
    base-path: src/main/resources/code_storage

  # --- Redis 설정 시작 ---
  data:
    redis:
      # 호스트: Docker Compose 환경에서는 'redis' 서비스 이름으로 컨테이너에 접근
      #         로컬에서 Redis를 직접 띄웠을 때는 'localhost'로 연결
      host: localhost
      # 포트: Redis 기본 포트 6379
      port: 6379

      # password: ${SPRING_DATA_REDIS_PASSWORD:} # Redis에 비밀번호가 있다면 여기에 설정 (환경 변수 또는 직접 입력)
      # ssl: false # SSL/TLS를 사용하지 않는 경우 (기본값)
      # timeout: 2000ms # 연결 타임아웃 (선택 사항)
      # lettuce: # Lettuce 클라이언트 설정 (선택 사항)
      #   pool:
      #     max-active: 8 # 풀에서 생성할 수 있는 최대 연결 수
      #     min-idle: 0   # 유휴 상태로 유지할 수 있는 최소 연결 수
      #     max-idle: 8   # 유휴 상태로 유지할 수 있는 최대 연결 수
      #     max-wait: -1ms # 풀에서 연결을 사용할 수 있을 때까지 블록 시간 (ms, -1은 무한대)
  # --- Redis 설정 끝 ---